# Generated by Django 3.1.6 on 2021-02-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='used_coupon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
